name: CI (Win32 Release)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure (VS2022 Win32)
        run: cmake --preset vs2022-win32-release

      - name: Build (Release)
        run: cmake --build --preset build-release --parallel

      - name: Run app
        run: .\build\win32-release\Release\widgecraft.exe
