name: CI (VS2022 Win32 Release)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 20

    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Configure Visual Studio 2022 Win32
        run: cmake --preset vs2022-win32-release

      - name: Build engine and UI sandbox
        run: cmake --build --preset build-release --parallel
